dist: trusty
sudo: false
language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=release RELEASE=yes
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=head
  allow_failures:
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=head
install:
- scripts/install-vault-${VAULT_BRANCH}.sh
- pip install tox
script:
- export PATH=$HOME/bin:$PATH
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make package ; else make test ; fi
deploy:
  provider: pypi
  user: lionelz
  password:
    secure: b+j7dbF0h8Inev5sTHGENW5Z2/fjIsNHxOxVb+XruZeDnGPTw6IUdOUp/zCzfQq00VZpVT+CN/lSCnQwUYjIGsXi5AhDK1pbOKRkgHFcKf/FvTxia17ErUV0Uu3VaVEFvkPuqeD60+GClIVfgrarXhFu02+lx2nW1uwO7eJpexyGxbwqtL6AIM9uhZovfYoVru4cyu/dNWAQLKAKUUg/oNWyt2sM3LNM9QG6kVmH3FBHi3931K+65rftDiRAgbosPzjU1apvd0Sb9MTFGlACM/AKr6STLZWhmu32Pe9n+vI7Rr9en97XyYGIepKZSvIAfa4Qr5y4al2k7Fa5YY3Trb9zV0yw6J1TdMQv7LqimgjoJIdsYqpbgqWMTOLXWmQk0oV5SwI59nQ0V+PrbZDKuQTcYjnHUTLHIATco8tj1vuVKgSotPFuaPVV9SzaNjJ+wfhb+fVoLu3hBf82etCeLlDb+2qFMrNyOH3NkI+zXyBdx5WQw09EFXcEc9wFfD9X8RDzBLs327RDX7kFf7f0A/+Pn/2r9QzL/NL88Sk+aREmzhQx4vFpBmweYXe6e48M244VwB+gsMvmEsOWeFFkZJW/J4Ozx4mmvbOxblrjRtucg2VzybCaBfA1RmF2rLq5SIWqJGmcbaBeRG4KgUeHaX8ZI7jpIjQ2XCgj/Qf5hWA=
  on:
    tags: true
    all_branches: true
    repo: Aloomaio/async-hvac
    condition: $RELEASE == "yes"
