dist: trusty
sudo: false
language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=release RELEASE=yes
  - python: '3.6'
    env: TOXENV=py36-flake8 VAULT_BRANCH=release RELEASE=yes
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=head
  allow_failures:
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=head
install:
- scripts/install-vault-${VAULT_BRANCH}.sh
- pip install tox
- pip install twine
script:
- export PATH=$HOME/bin:$PATH
- make clean distclean test package
deploy:
  provider: script
  skip_cleanup: true
  script: twine upload --username $PYPI_USERNAME --password $PYPI_PASSWORD --skip-existing dist/*
  on:
    tags: true
    repo: Aloomaio/async-hvac
    condition: $RELEASE == "yes"
