dist: trusty
sudo: false
language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=release RELEASE=yes
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=head
  allow_failures:
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=head
install:
- scripts/install-vault-${VAULT_BRANCH}.sh
- pip install tox
script:
- export PATH=$HOME/bin:$PATH
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make package ; else make test ; fi
deploy:
  skip_cleanup: true
  provider: pypi
  user: lionelz
  on:
    tags: true
    all_branches: true
    repo: Aloomaio/async-hvac
    condition: $RELEASE == "yes"
  password:
    secure: bB2I6X8iSbq9FbSymYp5DiFVPylnc2nhcqAAbEOmUEKU/KukjZe5FxaiRFyXUMCioPxXMgEIK0j/qm1ZoBff1iQIlD6zPKngSrDFxtKpVQuUlAoAXN9Zt+Maw7/OVm19k1DkNxizrcbuik6RJdo3PFpRXro+m1tyxQhFA1chmfHZGCNMi2xMp3IygAY8YBcgej6gSZsWS31qopYg9hAwh74QGnuUf3hgkYo4cIRrp+F3CMELtRsORAOUqsDGu2ehHy/2tG+UMlOnEsBgpwwSsRGTIxgurLdrfP5BOTCzp09AvRNMup7J9pAUmg5QM7ok2wpSn0NImHe09NKd18Ki1PopkGA0mLIFApFyt/2qDcKZj6WOG327r3ef/bCtWvabwuhMdUfDnyzYUEfj0heHsrJ02ww0pBDJqM4CChy7UwsMvrDG+FCRGtdOXMZOW6psi9XMZG4N4VskH9igUouVDu33x1dklTMv+c4jSB4TP1XrzJSI8R9q/v60PZpZj3GPf1gPCgkdsILKabNvI0oMI0ocmP0KJ4CbLGfl4UtGzNJ/rfhVLM6R/m+SBdEZLe/Rr1jl/NSWy6uKjwq1GSpTCmZ03iwg/XSnav+k33hHhgEHjLpVcRbDPfetL5YU6btAE8iqq9D5YJwtR9PKrig5cG8XEl/JT73tI81AFrq6X1c=
