dist: trusty
sudo: false
language: python
matrix:
  include:
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=release RELEASE=yes
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=head
  allow_failures:
  - python: '3.6'
    env: TOXENV=py36 VAULT_BRANCH=head
install:
- scripts/install-vault-${VAULT_BRANCH}.sh
- pip install tox
- echo [distutils]                                  > ~/.pypirc
- echo index-servers =                             >> ~/.pypirc
- echo "  pypi"                                    >> ~/.pypirc
- echo [pypi]                                      >> ~/.pypirc
- echo username=$PYPI_USERNAME                     >> ~/.pypirc
- echo password=$PYPI_PASSWORD                     >> ~/.pypirc
- chmod 600 ~/.pypirc
script:
- export PATH=$HOME/bin:$PATH
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make package ; else make test ; fi
deploy:
  provider: script
  script: python setup.py sdist upload -r pypi
  on:
    tags: true
    repo: Aloomaio/async-hvac
    condition: $RELEASE == "yes"
